apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    database: postgres
spec:
  ports:
    - port: 5432
      name: postgres
      nodePort: 30432
  type: NodePort
  selector:
    database: postgres
